// <auto-generated />
using System;
using Epik_PersonApp.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Epik_PersonApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117054310_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Epik_PersonApp.Domain.Entities.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TipoIdentificacionId")
                        .HasMaxLength(30)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasDatabaseName("IX_Persona_NumeroIdentificacion");

                    b.HasIndex("TipoIdentificacionId")
                        .IsUnique();

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("Epik_PersonApp.Domain.Entities.TipoIdentificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TiposIdentificacion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c0785e7-4863-48f7-ada7-ba819cf91e2d"),
                            Codigo = "CC",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Cédula de Ciudadanía",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("1a8d3e2f-4f23-4b0e-9d29-44eae48bbaa1"),
                            Codigo = "PA",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Pasaporte",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("2bfe05a9-df9a-4932-8a6a-511d6cccd8e6"),
                            Codigo = "TI",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Tarjeta de Identidad",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("3c2f1f66-9a65-44fc-b1ea-34ac2eab2553"),
                            Codigo = "CE",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Cédula de Extranjería",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("4e1c1499-8b27-4c65-b9f3-6a1918e842db"),
                            Codigo = "PEP",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Permiso Especial de Permanencia (PEP)",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("0c0785e7-4863-48f7-ada7-cfe3b67df097"),
                            Codigo = "RC",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Registro Civil",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Epik_PersonApp.Domain.Entities.Persona", b =>
                {
                    b.HasOne("Epik_PersonApp.Domain.Entities.TipoIdentificacion", "TipoIdentificacion")
                        .WithOne("Persona")
                        .HasForeignKey("Epik_PersonApp.Domain.Entities.Persona", "TipoIdentificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("Epik_PersonApp.Domain.Entities.TipoIdentificacion", b =>
                {
                    b.Navigation("Persona");
                });
#pragma warning restore 612, 618
        }
    }
}
